### ISSUE TITLE
Getting NPE, if a service has no filters

### ISSUE THREAD

**Issue by rshankar939** [flipkart-incubator/grpc-jexpress#22]
stack trace:
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@5a62b714
java.lang.NullPointerException
	at com.flipkart.gjex.grpc.interceptor.FilterInterceptor$3.onMessage(FilterInterceptor.java:130)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:737)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by regunathb** [comment]
Fixed and available in 1.3-SNAPSHOT release.
