### ISSUE TITLE
Getting NPE in bootup for 1.3-snapshot version

### ISSUE THREAD

**Issue by rshankar939** [flipkart-incubator/grpc-jexpress#23]
INFO: Initiating Jersey application, version Jersey: 2.6 2014-02-18 21:52:53...
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at com.flipkart.gjex.core.setup.Bootstrap.lambda$run$1(Bootstrap.java:233)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.flipkart.gjex.core.setup.Bootstrap.run(Bootstrap.java:228)
	at com.flipkart.gjex.core.Application.run(Application.java:110)
	at flipkart.cp.convert.cart.litesvc.CartLiteApplication.main(CartLiteApplication.java:20)
Caused by: java.lang.NullPointerException
	at com.flipkart.gjex.web.ResourceRegistrar.registerResources(ResourceRegistrar.java:68)
	at com.flipkart.gjex.grpc.service.ApiServer.doStart(ApiServer.java:59)
	at com.flipkart.gjex.core.service.AbstractService.start(AbstractService.java:56)
	at com.flipkart.gjex.core.setup.Bootstrap.lambda$run$1(Bootstrap.java:230)
	... 4 more

**Comment by regunathb** [comment]
Fixed and available in 1-3-SNAPSHOT version
